# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Red_Pitaya.xdc

# Block Designs: bd/my_DSP_Hardware/my_DSP_Hardware.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_DSP_Hardware || ORIG_REF_NAME==my_DSP_Hardware} -quiet] -quiet

# IP: bd/my_DSP_Hardware/ip/my_DSP_Hardware_processing_system7_0_0/my_DSP_Hardware_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_DSP_Hardware_processing_system7_0_0 || ORIG_REF_NAME==my_DSP_Hardware_processing_system7_0_0} -quiet] -quiet

# IP: bd/my_DSP_Hardware/ip/my_DSP_Hardware_my_AD_Converter_0_0/my_DSP_Hardware_my_AD_Converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_DSP_Hardware_my_AD_Converter_0_0 || ORIG_REF_NAME==my_DSP_Hardware_my_AD_Converter_0_0} -quiet] -quiet

# IP: bd/my_DSP_Hardware/ip/my_DSP_Hardware_my_DA_Converter_0_0/my_DSP_Hardware_my_DA_Converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_DSP_Hardware_my_DA_Converter_0_0 || ORIG_REF_NAME==my_DSP_Hardware_my_DA_Converter_0_0} -quiet] -quiet

# IP: bd/my_DSP_Hardware/ip/my_DSP_Hardware_my_Vector_Length_Mod_0_0/my_DSP_Hardware_my_Vector_Length_Mod_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_DSP_Hardware_my_Vector_Length_Mod_0_0 || ORIG_REF_NAME==my_DSP_Hardware_my_Vector_Length_Mod_0_0} -quiet] -quiet

# IP: bd/my_DSP_Hardware/ip/my_DSP_Hardware_my_Filter_0_0/my_DSP_Hardware_my_Filter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_DSP_Hardware_my_Filter_0_0 || ORIG_REF_NAME==my_DSP_Hardware_my_Filter_0_0} -quiet] -quiet

# XDC: bd/my_DSP_Hardware/my_DSP_Hardware_ooc.xdc
