# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kibii/OneDrive/Studienkolleg/Vivado/AD_DA_Exp/AD_DA_Exp.srcs/sources_1/bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_processing_system7_0_1/my_AD_DA_Exp_processing_system7_0_1.xci
# IP: The module: 'my_AD_DA_Exp_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kibii/OneDrive/Studienkolleg/Vivado/AD_DA_Exp/AD_DA_Exp.srcs/sources_1/bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_processing_system7_0_1/my_AD_DA_Exp_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_AD_DA_Exp_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/kibii/OneDrive/Studienkolleg/Vivado/AD_DA_Exp/AD_DA_Exp.srcs/sources_1/bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_processing_system7_0_1/my_AD_DA_Exp_processing_system7_0_1.xci
# IP: The module: 'my_AD_DA_Exp_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kibii/OneDrive/Studienkolleg/Vivado/AD_DA_Exp/AD_DA_Exp.srcs/sources_1/bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_processing_system7_0_1/my_AD_DA_Exp_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_AD_DA_Exp_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
