# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pabele/HTWG/Skripte/SoC/Labor_Vorlesung/02d_Block_Design_erzeugen/Vivado_Projekte/AD_DA_Exp/AD_DA_Exp.srcs/sources_1/bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_processing_system7_0_0/my_AD_DA_Exp_processing_system7_0_0.xci
# IP: The module: 'my_AD_DA_Exp_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pabele/HTWG/Skripte/SoC/Labor_Vorlesung/02d_Block_Design_erzeugen/Vivado_Projekte/AD_DA_Exp/AD_DA_Exp.srcs/sources_1/bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_processing_system7_0_0/my_AD_DA_Exp_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_AD_DA_Exp_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/pabele/HTWG/Skripte/SoC/Labor_Vorlesung/02d_Block_Design_erzeugen/Vivado_Projekte/AD_DA_Exp/AD_DA_Exp.srcs/sources_1/bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_processing_system7_0_0/my_AD_DA_Exp_processing_system7_0_0.xci
# IP: The module: 'my_AD_DA_Exp_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pabele/HTWG/Skripte/SoC/Labor_Vorlesung/02d_Block_Design_erzeugen/Vivado_Projekte/AD_DA_Exp/AD_DA_Exp.srcs/sources_1/bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_processing_system7_0_0/my_AD_DA_Exp_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_AD_DA_Exp_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
