# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Red_Pitaya.xdc

# Block Designs: bd/my_AD_DA_Exp/my_AD_DA_Exp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Exp || ORIG_REF_NAME==my_AD_DA_Exp} -quiet] -quiet

# IP: bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_my_Vector_Length_Mod_0_0/my_AD_DA_Exp_my_Vector_Length_Mod_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Exp_my_Vector_Length_Mod_0_0 || ORIG_REF_NAME==my_AD_DA_Exp_my_Vector_Length_Mod_0_0} -quiet] -quiet

# IP: bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_my_DA_Converter_0_0/my_AD_DA_Exp_my_DA_Converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Exp_my_DA_Converter_0_0 || ORIG_REF_NAME==my_AD_DA_Exp_my_DA_Converter_0_0} -quiet] -quiet

# IP: bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_my_AD_Converter_0_0/my_AD_DA_Exp_my_AD_Converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Exp_my_AD_Converter_0_0 || ORIG_REF_NAME==my_AD_DA_Exp_my_AD_Converter_0_0} -quiet] -quiet

# IP: bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_my_Vector_Length_Mod_1_0/my_AD_DA_Exp_my_Vector_Length_Mod_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Exp_my_Vector_Length_Mod_1_0 || ORIG_REF_NAME==my_AD_DA_Exp_my_Vector_Length_Mod_1_0} -quiet] -quiet

# IP: bd/my_AD_DA_Exp/ip/my_AD_DA_Exp_processing_system7_0_1/my_AD_DA_Exp_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Exp_processing_system7_0_1 || ORIG_REF_NAME==my_AD_DA_Exp_processing_system7_0_1} -quiet] -quiet

# XDC: bd/my_AD_DA_Exp/my_AD_DA_Exp_ooc.xdc
