# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AXI_BRAM/AXI_BRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_BRAM || ORIG_REF_NAME==AXI_BRAM} -quiet] -quiet

# IP: bd/AXI_BRAM/ip/AXI_BRAM_processing_system7_0_0/AXI_BRAM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_BRAM_processing_system7_0_0 || ORIG_REF_NAME==AXI_BRAM_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_BRAM/ip/AXI_BRAM_blk_mem_gen_0_0/AXI_BRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_BRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==AXI_BRAM_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/AXI_BRAM/ip/AXI_BRAM_axi_bram_ctrl_0_0/AXI_BRAM_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_BRAM_axi_bram_ctrl_0_0 || ORIG_REF_NAME==AXI_BRAM_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/AXI_BRAM/ip/AXI_BRAM_axi_bram_ctrl_1_0/AXI_BRAM_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_BRAM_axi_bram_ctrl_1_0 || ORIG_REF_NAME==AXI_BRAM_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/AXI_BRAM/ip/AXI_BRAM_axi_smc_0/AXI_BRAM_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_BRAM_axi_smc_0 || ORIG_REF_NAME==AXI_BRAM_axi_smc_0} -quiet] -quiet

# IP: bd/AXI_BRAM/ip/AXI_BRAM_rst_ps7_0_50M_0/AXI_BRAM_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXI_BRAM_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_BRAM_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/AXI_BRAM/AXI_BRAM_ooc.xdc
