# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Red_Pitaya.xdc

# Block Designs: bd/my_AD_DA_Direct/my_AD_DA_Direct.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Direct || ORIG_REF_NAME==my_AD_DA_Direct} -quiet] -quiet

# IP: bd/my_AD_DA_Direct/ip/my_AD_DA_Direct_processing_system7_0_0/my_AD_DA_Direct_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Direct_processing_system7_0_0 || ORIG_REF_NAME==my_AD_DA_Direct_processing_system7_0_0} -quiet] -quiet

# IP: bd/my_AD_DA_Direct/ip/my_AD_DA_Direct_my_AD_Converter_0_0/my_AD_DA_Direct_my_AD_Converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Direct_my_AD_Converter_0_0 || ORIG_REF_NAME==my_AD_DA_Direct_my_AD_Converter_0_0} -quiet] -quiet

# IP: bd/my_AD_DA_Direct/ip/my_AD_DA_Direct_my_DA_Converter_0_0/my_AD_DA_Direct_my_DA_Converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==my_AD_DA_Direct_my_DA_Converter_0_0 || ORIG_REF_NAME==my_AD_DA_Direct_my_DA_Converter_0_0} -quiet] -quiet

# XDC: bd/my_AD_DA_Direct/my_AD_DA_Direct_ooc.xdc
